env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:

  - id: pmon2
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./cmd/pmon2/pmon2.go
    flags:
      - -trimpath
#    ldflags:

  - id: pmond
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    binary: "pmond"
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./cmd/pmond/pmond.go
    flags:
      - -trimpath
#    ldflags:

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy



archives:
  - id: pmon2
    builds:
      - pmon2
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"



  - id: pmond
    builds:
      - pmond
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - config/config.yml
      - service/centos7/pmon2.service
      - service/centos6/*.conf
      - logrotate/pmon2
      - auto-complete/bash/pmon2.sh


nfpms:
  - id: "other_linux"
    license: AGPL 3.0
    homepage: https://github.com/ntt360/pmon2
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: ntt360
    bindir: /usr/local/pmon2/bin
    builds:
      - pmond
      - pmon2
    replacements:
      amd64: x86-64
      386: x86_32

    empty_folders:
      - /etc/pmon2/
      - /etc/pmon2/config/
      - /usr/local/pmon2/bin
      - /usr/local/pmon2/service/centos6/
      - /usr/local/pmon2/service/centos7/
      - /usr/local/pmon2/auto-complete/bash/
      - /usr/local/pmon2/logrotate/
    files:
      "auto-complete/bash/pmon2.sh": "/usr/local/pmon2/auto-complete/bash/pmon2.sh"
      "service/centos6/*.conf": "/usr/local/pmon2/service/centos6/"
      "service/centos7/pmon2.service": "/usr/local/pmon2/service/centos7/pmon2.service"
      "logrotate/pmon2": "/usr/local/pmon2/logrotate/pmon2"
    config_files:
      "config/config.yml": "/etc/pmon2/config/config.yml"

    scripts:
#      执行不同的安装文件
      postinstall: "auto-complete/scripts/other_install.sh"
      postremove: "auto-complete/scripts/uninstall.sh"

  - id: "centos6"
    license: AGPL 3.0
    homepage: https://github.com/ntt360/pmon2
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_centos6_{{ .Arch }}"
    formats:
      - rpm
    maintainer: ntt360
    bindir: /usr/local/pmon2/bin
    builds:
      - pmond
      - pmon2
    replacements:
      amd64: x86-64
      386: x86_32

    empty_folders:
      - /etc/pmon2/
      - /etc/pmon2/config/
      - /usr/local/pmon2/bin
      - /usr/local/pmon2/service/centos6/
      - /usr/local/pmon2/service/centos7/
      - /usr/local/pmon2/auto-complete/bash/
      - /usr/local/pmon2/logrotate/
    files:
      "auto-complete/bash/pmon2.sh": "/usr/local/pmon2/auto-complete/bash/pmon2.sh"
      "service/centos6/*.conf": "/usr/local/pmon2/service/centos6/"
      "service/centos7/pmon2.service": "/usr/local/pmon2/service/centos7/pmon2.service"
      "logrotate/pmon2": "/usr/local/pmon2/logrotate/pmon2"
    config_files:
      "config/config.yml": "/etc/pmon2/config/config.yml"
    scripts:
#      执行不同的安装文件
      postinstall: "auto-complete/scripts/centos6_install.sh"
      postremove: "auto-complete/scripts/uninstall.sh"

